name: nex_media_picker
description: A comprehensive Flutter plugin for picking and processing images, videos, and documents with theme support.
version: 0.0.2
homepage: https://github.com/dileep-nex/nex_media_picker/blob/main/example/lib/main.dart
repository: https://github.com/dileep-nex/nex_media_picker

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.0
  image_cropper: ^10.0.0+1
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  provider: ^6.1.5+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
